### ISSUE TITLE
Add Multiplayer

### ISSUE THREAD

**Issue by VTVDV** [DP94/RogueTrader#1]
Now that we can walk around the ship, we should add the ability for another person to do so too!

With multiplayer there are two "roles" to consider as far as we're concerned:

-  One player (easiest way is host) will be a GM and will need to spawn in as a spectator.
- Everyone else will be able to walk around the environment.

Thom has defined a Captain as a role, but for now if we stick with these two we can build on the role later.

**Comment by DP94** [comment]
@VTVDV Do we have any idea on what the UI should look like for the lobby?

**Comment by VTVDV** [comment]
Hmm, probs worth talking to Thom about, do we need a ready-up option or anything like that or should it just be host starts a game (and is auto made GM) and people put in an IP to join? For now I think we can streamline it and flesh it out later if need be right?

**Comment by DP94** [comment]
Went for this in the end - we can raise issues to neaten and improve this
![image](https://user-images.githubusercontent.com/14276637/151261641-a3bf6f10-e937-4c17-a4d7-066c071ae607.png)
